---

- name: Create jenkins dir
  shell: mkdir -p  ~jenkins/jenkins_home

- name: Copy docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "~jenkins/docker-compose.yml"
    mode: "0755"
- name: Run docker-compose for jenkins install
  shell: docker-compose -f ~jenkins/docker-compose.yml up -d
