---
filebeat.inputs:
- type: docker
  combine_partial: true
  containers:
    path: "/usr/share/dockerlogs/data"
    ids:
      - "*"

#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]
output.logstash:
  hosts: ["logstash:5044"]

