version: '2.4'
services:
  nginx:
    image: goodvine/websrv:v1
    deploy:
      replicas: 1
    ports:
     - '8080:80'
    volumes:
     vhost.conf:/etc/nginx/conf.d/vhost.conf

  app:
    image: javahello
    depends_on:
     - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:var/lib/mysql"

